version: '3.8'
services:
  github-mcp:
    image: anthropic/github-mcp:latest
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3001:3000"
    restart: always
  
  fs-mcp:
    image: anthropic/fs-mcp:latest
    volumes:
      - .:/workspace
    ports:
      - "3002:3000"
    restart: always
  
  claude-automation-mcp:
    image: anthropic/automation-mcp:latest
    environment:
      - REPO_PATH=/workspace
    volumes:
      - .:/workspace
    ports:
      - "3003:3000"
    restart: always