import type { ChapterExperience, ChapterId } from '../types';

export const CHAPTER_SCENES: Record<ChapterId, ChapterExperience> = {
  ch1: {
    chapterId: 'ch1',
    visualTheme: 'Ego/Self depth field',
    sceneModule: '../visualizations/chapters/ch1/ThreeEgoViz.js',
    motionGrammar: 'cyclical-return',
    fallbackSummary: 'A still depth diagram places the ego as a small surface light, splits its somatic and psychic roots, and sets the deeper Self as the whole field.',
    checkpoints: ['Locate the ego as a small surface light.', 'Distinguish the somatic root from the psychic root.', 'Explain why the Self is larger than the conscious I.'],
    panels: [
      { id: 'ego-light', kicker: 'Orientation', title: 'A point of consciousness', body: 'Begin with the ego as a bright, local center of identity and attention.', insight: 'The ego is necessary, but not total.' },
      { id: 'roots', kicker: 'Depth', title: 'Two roots feed the I', body: 'Body, instinct, memory, dream, and intuition pull the ego into a deeper life-field.', insight: 'Consciousness rests on what it cannot fully command.' },
      { id: 'self-depth', kicker: 'Wholeness', title: 'The Self holds the field', body: 'The final view scales the ego against a larger ordering center below it.', insight: 'The journey starts by scaling the I correctly.' },
    ],
  },
  ch2: {
    chapterId: 'ch2',
    visualTheme: 'Shadow mirror and projection arcs',
    sceneModule: '../visualizations/chapters/ch2/ThreeShadowViz.js',
    motionGrammar: 'opposition',
    fallbackSummary: 'A split mirror sets ego and shadow as related opposites; projection arcs throw the refused image outward, then return it as material for integration.',
    checkpoints: ['Find the refused likeness in the mirror.', 'Trace projection outward and back.', 'Describe integration without erasing the shadow.'],
    panels: [
      { id: 'mirror', kicker: 'Opposition', title: 'The refused likeness', body: 'The shadow appears as the ego sees a distorted version of what it rejects.', insight: 'Recognition begins when the image becomes personal.' },
      { id: 'projection', kicker: 'Projection', title: 'Thrown outward', body: 'Shadow contents look like they belong to the outside world when they are not owned.', insight: 'Projection makes inner conflict look external.' },
      { id: 'integration', kicker: 'Integration', title: 'Return without collapse', body: 'Integration keeps the darkness visible while placing it back in relation.', insight: 'The ego grows by admitting what it excludes.' },
    ],
  },
  ch3: {
    chapterId: 'ch3',
    visualTheme: 'Anima/animus orbital relation',
    sceneModule: '../visualizations/chapters/ch3/ThreeSyzygyViz.js',
    motionGrammar: 'integration',
    fallbackSummary: 'A relation lab sets anima and animus as two symbolic poles: projection makes the inner image appear outside, orbit keeps the tension readable, and conjunction appears as a brief symbolic union rather than a final fusion.',
    checkpoints: ['Name anima and animus as symbolic poles, not fixed identities.', 'Trace projection outward and back into relation.', 'Explain why conjunction flashes and then releases into motion.'],
    panels: [
      { id: 'pair', kicker: 'Syzygy', title: 'Two poles, one psyche', body: 'Anima and animus mediate relation to the unconscious without becoming fixed identities.', insight: 'The psyche thinks in living opposites.' },
      { id: 'orbit', kicker: 'Relation', title: 'Projection becomes orbit', body: 'Attraction, resistance, and return become readable only when the image stays in relation.', insight: 'Wholeness needs tension, not sameness.' },
      { id: 'union', kicker: 'Conjunction', title: 'Union flashes, then moves', body: 'Alignment forms a symbolic mandorla, then releases back into motion.', insight: 'Integration is rhythmic, not static.' },
    ],
  },
  ch4: {
    chapterId: 'ch4',
    visualTheme: 'Self mandala and quaternity',
    sceneModule: '../visualizations/chapters/ch4/ThreeSelfViz.js',
    motionGrammar: 'cyclical-return',
    fallbackSummary: 'Concentric mandala rings arrange ego, shadow, anima/animus, and Self into a fourfold ordering image.',
    checkpoints: ['Find the center.', 'Trace the fourfold structure.', 'Connect mandala and Self.'],
    panels: [
      { id: 'seed', kicker: 'Center', title: 'The small center opens', body: 'The Self appears first as an unimpressive point, then as ordering totality.', insight: 'The deepest center is not the loudest form.' },
      { id: 'quaternity', kicker: 'Fourfold', title: 'Wholeness takes four directions', body: 'Four psychic functions make balance visible.', insight: 'A totality image must include more than perfection.' },
      { id: 'mandala', kicker: 'Mandala', title: 'Chaos receives a form', body: 'Circular order contains psychic conflict without flattening it.', insight: 'The Self orders by holding difference.' },
    ],
  },
  ch5: {
    chapterId: 'ch5',
    visualTheme: 'Christ symbol and excluded fourth',
    sceneModule: '../visualizations/chapters/ch5/ThreeChristViz.js',
    motionGrammar: 'opposition',
    fallbackSummary: 'A luminous cross and three-plus-one gem field reveal the Christ symbol as powerful, psychologically one-sided, and pressured by the excluded fourth.',
    checkpoints: ['See the bright trinity.', 'Find the excluded fourth.', 'Relate Christ symbol to Self.'],
    panels: [
      { id: 'cross', kicker: 'Cross', title: 'A Western Self image', body: 'The Christ symbol carries the axis of wholeness for Western imagination.', insight: 'A religious image can be read psychologically without reducing it.' },
      { id: 'fourth', kicker: 'Fourth', title: 'The fourth is missing', body: 'The rejected dark element marks the incompleteness of one-sided light.', insight: 'Wholeness asks what perfection excludes.' },
      { id: 'tree', kicker: 'Root', title: 'The roots go downward', body: 'The symbol becomes total only when it reaches into the depths it resists.', insight: 'The Self includes the counter-pole.' },
    ],
  },
  ch6: {
    chapterId: 'ch6',
    visualTheme: 'Zodiac fish aeon wheel',
    sceneModule: '../visualizations/chapters/ch6/ThreeFishViz.js',
    motionGrammar: 'cyclical-return',
    fallbackSummary: 'Opposing fish circle through zodiacal time, making the aeon visible as symbolic history.',
    checkpoints: ['Track the two fish.', 'Locate the aeon cycle.', 'Connect opposition to history.'],
    panels: [
      { id: 'fish', kicker: 'Pisces', title: 'Two fish, two directions', body: 'The fish sign images a split current inside the Christian aeon.', insight: 'A symbol can carry its own contradiction.' },
      { id: 'zodiac', kicker: 'Aeon', title: 'History gains a wheel', body: 'Astrological time frames collective imagination as recurrence and transition.', insight: 'The book reads symbols across centuries.' },
      { id: 'transition', kicker: 'Threshold', title: 'The age turns slowly', body: 'The visual cycle points to a transition that is symbolic before it is literal.', insight: 'Aeonic change is a psychic weather system.' },
    ],
  },
  ch7: {
    chapterId: 'ch7',
    visualTheme: 'Prophecy field and historical anxiety',
    sceneModule: '../visualizations/chapters/ch7/ThreeProphecyViz.js',
    motionGrammar: 'transformation',
    fallbackSummary: 'A time-field of prophetic images shows how collective anxiety condenses around symbolic dates and transitions.',
    checkpoints: ['Separate event from interpretation.', 'Track projection in history.', 'Find the collective pattern.'],
    panels: [
      { id: 'prophecy', kicker: 'Prophecy', title: 'Meaning under pressure', body: 'Prophetic imagination forms when history is charged by unconscious expectation.', insight: 'The psyche makes time symbolic.' },
      { id: 'collective', kicker: 'Collective', title: 'Private fear becomes shared image', body: 'Collective anxiety seeks forms that can hold it.', insight: 'Symbols organize what facts alone cannot.' },
      { id: 'threshold', kicker: 'Threshold', title: 'The future looks backward', body: 'Prediction often repeats older archetypal images in new dress.', insight: 'Prophecy reveals the present psyche.' },
    ],
  },
  ch8: {
    chapterId: 'ch8',
    visualTheme: 'Fish symbol historical strata',
    sceneModule: '../visualizations/chapters/ch8/ThreeHistoricalViz.js',
    motionGrammar: 'transformation',
    fallbackSummary: 'Layered historical strata show the fish motif accumulating meanings rather than carrying one fixed definition.',
    checkpoints: ['Read the layers.', 'Notice symbol drift.', 'Connect history to psyche.'],
    panels: [
      { id: 'strata', kicker: 'History', title: 'Symbols gather sediment', body: 'The fish motif becomes meaningful through accumulation.', insight: 'A symbol is a history of uses.' },
      { id: 'christian', kicker: 'Early Image', title: 'The fish becomes a carrier', body: 'Christian symbolism gives the fish a salvific charge.', insight: 'A small sign can hold a total world.' },
      { id: 'modern', kicker: 'Afterlife', title: 'Old images keep speaking', body: 'Historical meanings continue below later interpretations.', insight: 'The unconscious preserves symbolic depth.' },
    ],
  },
  ch9: {
    chapterId: 'ch9',
    visualTheme: 'Ambivalent fish and ouroboros mirror',
    sceneModule: '../visualizations/chapters/ch9/ThreeOuroborosViz.js',
    motionGrammar: 'opposition',
    fallbackSummary: 'A circular fish-serpent image holds salvation and shadow together as one ambivalent totality.',
    checkpoints: ['Find both meanings.', 'Hold the contradiction.', 'Connect ambivalence to the Self.'],
    panels: [
      { id: 'ambivalence', kicker: 'Paradox', title: 'The fish has a double edge', body: 'The symbol carries blessing and threat at once.', insight: 'Ambivalence is not confusion; it is structure.' },
      { id: 'ouroboros', kicker: 'Return', title: 'The image eats its tail', body: 'The circular form shows opposition returning into itself.', insight: 'The psyche circles what it cannot solve linearly.' },
      { id: 'shadow-fish', kicker: 'Shadow', title: 'Light casts its fish-shadow', body: 'The Antichrist pole belongs to the same symbolic field.', insight: 'A total image includes its antagonist.' },
    ],
  },
  ch10: {
    chapterId: 'ch10',
    visualTheme: 'Alchemical fish vessel',
    sceneModule: '../visualizations/chapters/ch10/ThreeAlchemyViz.js',
    motionGrammar: 'transformation',
    fallbackSummary: 'An alchemical vessel transforms the fish motif through darkening, whitening, illumination, and reddening.',
    checkpoints: ['Name the vessel.', 'Track transformation stages.', 'Connect fish and prima materia.'],
    panels: [
      { id: 'vessel', kicker: 'Alchemy', title: 'The fish enters the opus', body: 'Alchemy turns inherited symbols into transformation procedures.', insight: 'The symbol becomes a process.' },
      { id: 'prima', kicker: 'Prima Materia', title: 'Begin with the mixed thing', body: 'Transformation starts with confused, conflicted material.', insight: 'The raw state is not a mistake.' },
      { id: 'opus', kicker: 'Opus', title: 'Matter teaches psyche', body: 'The vessel makes inner transformation visible as stages.', insight: 'Alchemy gives psychology a theater.' },
    ],
  },
  ch11: {
    chapterId: 'ch11',
    visualTheme: 'Mercurius and opus wheel',
    sceneModule: '../visualizations/chapters/ch11/ThreeTreeViz.js',
    motionGrammar: 'transformation',
    fallbackSummary: 'A branching alchemical tree and opus cycle show Mercurius mediating matter, spirit, poison, and medicine.',
    checkpoints: ['Locate Mercurius as mediator.', 'Trace the opus cycle.', 'Connect lapis and coniunctio.'],
    panels: [
      { id: 'mercurius', kicker: 'Mediator', title: 'The slippery middle', body: 'Mercurius joins what stable concepts keep apart.', insight: 'The mediator is ambivalent by nature.' },
      { id: 'opus-wheel', kicker: 'Opus', title: 'Transformation repeats', body: 'Alchemical work moves through recurring operations.', insight: 'Change returns to deepen itself.' },
      { id: 'lapis', kicker: 'Stone', title: 'The goal is a formed paradox', body: 'The lapis images stabilized union, not purity.', insight: 'Completion keeps the opposites alive.' },
    ],
  },
  ch12: {
    chapterId: 'ch12',
    visualTheme: 'Christian and alchemical root system',
    sceneModule: '../visualizations/chapters/ch12/ThreeUnusViz.js',
    motionGrammar: 'integration',
    fallbackSummary: 'A branching root system connects Christian and alchemical symbols as parallel languages of psychic transformation.',
    checkpoints: ['Identify the two traditions.', 'Notice the shared roots.', 'Avoid literal reduction.'],
    panels: [
      { id: 'background', kicker: 'Method', title: 'Read symbolically', body: 'The chapter asks for a psychological reading that does not flatten religion or history.', insight: 'Interpretation needs restraint.' },
      { id: 'roots', kicker: 'Genealogy', title: 'Different languages share roots', body: 'Christian and alchemical images often carry similar psychic structures.', insight: 'Symbols migrate between systems.' },
      { id: 'bridge', kicker: 'Bridge', title: 'The old image becomes inward', body: 'The same motifs turn from doctrine toward psychological experience.', insight: 'Aion reads tradition as inner drama.' },
    ],
  },
  ch13: {
    chapterId: 'ch13',
    visualTheme: 'Gnostic emanation and quaternio',
    sceneModule: '../visualizations/chapters/ch13/ThreeQuaternioViz.js',
    motionGrammar: 'cyclical-return',
    fallbackSummary: 'Nested quaternary layers and emanation spheres show Gnostic images approaching the Self through paradox.',
    checkpoints: ['See the emanation layers.', 'Find the fourfold pattern.', 'Relate Gnostic motifs to Self.'],
    panels: [
      { id: 'gnosis', kicker: 'Gnosis', title: 'Knowledge becomes an image', body: 'Gnostic motifs give psychic totality a cosmic grammar.', insight: 'Cosmology can image interior order.' },
      { id: 'quaternio', kicker: 'Fourfold', title: 'The Self repeats as four', body: 'Fourfold structures recur as attempts to picture completeness.', insight: 'Wholeness has a structural signature.' },
      { id: 'paradox', kicker: 'Paradox', title: 'Wisdom includes rupture', body: 'Gnostic symbols often hold fullness and fall together.', insight: 'The Self is approached through contradiction.' },
    ],
  },
  ch14: {
    chapterId: 'ch14',
    visualTheme: 'Final aeon mandala synthesis',
    sceneModule: '../visualizations/chapters/ch14/ThreeAeonFinalViz.js',
    motionGrammar: 'integration',
    fallbackSummary: 'A final mandala gathers ego, shadow, syzygy, fish, alchemy, and Gnosis into a living image of the Self.',
    checkpoints: ['Gather the earlier motifs.', 'Trace the ego/Self axis.', 'Name the final dynamic.'],
    panels: [
      { id: 'gather', kicker: 'Synthesis', title: 'The book folds into one image', body: 'Earlier motifs return as parts of a larger psychic architecture.', insight: 'Completion is a constellation, not a slogan.' },
      { id: 'axis', kicker: 'Axis', title: 'Ego and Self are held together', body: 'The final structure preserves relation between conscious standpoint and totality.', insight: 'The goal is right relation.' },
      { id: 'aeon', kicker: 'Aeon', title: 'The image keeps moving', body: 'The Self is dynamic, cyclical, and historical.', insight: 'Aion ends with motion, not closure.' },
    ],
  },
};

export const SCENE_LOADERS: Record<ChapterId, () => Promise<unknown>> = {
  ch1: () => import('../../visualizations/chapters/ch1/ThreeEgoViz.js'),
  ch2: () => import('../../visualizations/chapters/ch2/ThreeShadowViz.js'),
  ch3: () => import('../../visualizations/chapters/ch3/ThreeSyzygyViz.js'),
  ch4: () => import('../../visualizations/chapters/ch4/ThreeSelfViz.js'),
  ch5: () => import('../../visualizations/chapters/ch5/ThreeChristViz.js'),
  ch6: () => import('../../visualizations/chapters/ch6/ThreeFishViz.js'),
  ch7: () => import('../../visualizations/chapters/ch7/ThreeProphecyViz.js'),
  ch8: () => import('../../visualizations/chapters/ch8/ThreeHistoricalViz.js'),
  ch9: () => import('../../visualizations/chapters/ch9/ThreeOuroborosViz.js'),
  ch10: () => import('../../visualizations/chapters/ch10/ThreeAlchemyViz.js'),
  ch11: () => import('../../visualizations/chapters/ch11/ThreeTreeViz.js'),
  ch12: () => import('../../visualizations/chapters/ch12/ThreeUnusViz.js'),
  ch13: () => import('../../visualizations/chapters/ch13/ThreeQuaternioViz.js'),
  ch14: () => import('../../visualizations/chapters/ch14/ThreeAeonFinalViz.js'),
};
